FROM caspia/seekoff-webapp:latest

MAINTAINER R. Kent James <rkent@caspia.com>
LABEL Description="Webapp for offline Stack Exchange search" Vendor="openprisoneducation.com" Version="0.1"
LABEL version=0.1

ENV VIRTUAL_HOST=seekoff.ed
